#!/bin/bash
# Update and install dependencies
apt update;
apt-get install python3 -y;
apt-get install python3-pip -y;
pip3 install flask

# Prompt user for API key
read -p "Please enter your API key:" API_KEY


# Change directory and remove old backend if exists
cd /usr/bin/
rm -rf backend
rm -rf /etc/systemd/system/backend.service

# Download new backend
wget -q -O /usr/bin/backend "https://raw.githubusercontent.com/bokir-tampan/nenen/refs/heads/main/ajunganteng"

# Replace the 'meki' key with the new API key entered by the user
sed -i "s/'meki'/'$API_KEY'/" /usr/bin/backend

# Create backend service file
cat >/etc/systemd/system/backend.service << EOF
[Unit]
Description=My Project
After=network.target

[Service]
WorkingDirectory=/root
ExecStart=/usr/bin/python3 /usr/bin/backend  
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# Reload and enable the service
systemctl daemon-reload
systemctl restart backend
systemctl enable backend
